app = "hola-recep-voice"
primary_region = "syd"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "performance-1x"
  memory = "2gb"
